import AsyncStorage from '@react-native-async-storage/async-storage';
import * as FileSystem from 'expo-file-system/legacy';
import { manipulateAsync, SaveFormat } from 'expo-image-manipulator';
import { LoggedMemory, dateKey, getLoggedMemories } from './memoryLog';
import { getAllPhotoSources, getAllPhotoTimestamps } from './photoMeta';
import { chatCompletion, textProviders, visionAvailable, visionProviders } from './aiProviders';
import { resolvePhotoUri } from './photoUri';

// "Assumed Memory" — when a day has photos but the app can only guess what
// actually happened, this reconstructs a plausible, clearly-speculative
// account from the photos alone: what's in them, and when each was taken.
// Read-only and dismissible — it never becomes the user's real logged Day
// memory (see memoryLog.ts), it's just the AI's best guess floating
// alongside it on the Timeline.

export function assumedMemoryAvailable(): boolean {
  return visionAvailable();
}

// The day's own words, as one string — what the analysis is given as
// ground truth to complement, and part of the cache signature.
//
// This MUST be derived identically everywhere (Timeline, Day detail, the
// background pass). It previously wasn't: each caller built it slightly
// differently, so they each computed a different signature for the same
// day and kept regenerating each other's work in a loop. Always sorted by
// time so the string is stable regardless of what order the caller's list
// happened to be in.
export function dayLoggedText(memories: LoggedMemory[]): string {
  return [...memories]
    .sort((a, b) => a.takenAt.localeCompare(b.takenAt))
    .map((m) => m.text?.trim())
    .filter(Boolean)
    .join(' ');
}

// Bump whenever the analysis prompt changes in a way that should rewrite
// existing summaries. Cached records generated under an older version are
// treated as stale and regenerated by the normal background pass — no
// manual cache wipe, and no re-analysing everything for prompt tweaks that
// don't warrant it.
//   1 — original ("warm narrative", heavy hedging)
//   2 — direct, concrete tone; no mood/filler words
//   3 — screenshots/saved images no longer treated as events of that day
export const PROMPT_VERSION = 3;

export type AssumedMemory = {
  summary: string;
  // Translated copies of `summary`, keyed by language code — filled in on
  // demand the first time the user taps "Translate" for that language, then
  // cached alongside the original so it's never re-translated.
  translations?: Record<string, string>;
  generatedAt: string;
  signature: string;
  // Which prompt wrote this summary. Absent on records from before
  // versioning existed, which correctly reads as stale.
  promptVersion?: number;
};

// A cached record is only reusable if it was built from the same photos AND
// by the current prompt.
function isFresh(cached: AssumedMemory | null | undefined, signature: string): boolean {
  // Deliberately does NOT require the current PROMPT_VERSION.
  //
  // It used to, which meant every prompt tweak silently invalidated every
  // day at once — hundreds of queued vision calls on every single app
  // launch, saturating the account's tokens-per-minute budget for 20+
  // minutes and starving the Ask chat of the quota it needs to answer
  // anything. A wording improvement is never worth breaking the main
  // feature of the app.
  //
  // So: an existing analysis is kept regardless of which prompt wrote it.
  // Only genuinely new or changed days (different photos / edited logged
  // text) cost an API call. PROMPT_VERSION is still recorded on new
  // records, so a deliberate, user-triggered rewrite can find the old ones
  // later — see regenerateStaleAnalyses().
  return !!cached && cached.signature === signature;
}

// Days whose analysis predates the current prompt. Nothing calls this
// automatically — it exists so a rewrite can be offered as an explicit,
// opt-in action rather than something that quietly eats the budget.
export async function countOutdatedAnalyses(): Promise<number> {
  const all = await getAllAssumedMemories();
  return Object.values(all).filter((r) => r.promptVersion !== PROMPT_VERSION).length;
}

// Drops the cached analyses written by older prompts so the normal
// background pass regenerates them in the current tone. Opt-in only.
export async function regenerateStaleAnalyses(): Promise<number> {
  const all = await getAllAssumedMemories();
  const stale = Object.entries(all).filter(([, r]) => r.promptVersion !== PROMPT_VERSION);
  await AsyncStorage.multiRemove(stale.map(([day]) => CACHE_PREFIX + day));
  return stale.length;
}

// Languages the translate button offers. Egyptian Arabic only for now — add
// more entries here later, the button/logic below is already generic.
// `label` is what the button shows; `instruction` is the dialect fed to the
// translation prompt.
export const ASSUMED_MEMORY_LANGUAGES: Record<string, { label: string; instruction: string }> = {
  ar: {
    label: 'Arabic',
    // Dialect drift is the whole problem here — a general "write Egyptian
    // Arabic" instruction reliably produces a Fusha/Egyptian mix that reads
    // wrong. Concrete word-level anchors are what actually hold it.
    instruction: `Egyptian colloquial Arabic (مصري عامية) — the way people actually talk and text in Cairo.

NEVER Modern Standard Arabic (فصحى), and never a mix of the two. Banned Fusha words and constructions: قمت بـ، ثم، لقد، سوف، حيث، الذي/التي، تم، بعد ذلك، تناولت، توجهت، استمتعت بـ.
Use the everyday equivalents instead: كنت، رحت، قعدت، خدت، اتفرجت، بعدين، وبعد كده، شوية، كده، عشان، أوي، برضه، إمبارح، النهاردة.

No tashkeel. Write it the way it gets typed in a chat, not the way it's written in a newspaper.`,
  },
};

// `source` is the provenance label when there is one ('screenshot',
// 'whatsapp', …). A labelled image was SAVED that day, not taken that day —
// which the analysis has to treat completely differently.
export type TimedPhoto = { uri: string; takenAt: number; source?: string };

const CACHE_PREFIX = 'assumedMemory:';
const DISMISSED_KEY = 'assumedMemoryDismissed';

// Photos this close together are almost certainly the same moment (a burst,
// or a couple of retakes) — only the first of a cluster is analyzed.
const DUPLICATE_GAP_MS = 10_000;
// Hard ceiling regardless of dedup, so one huge day never balloons a single
// request — sampled evenly across the day if still over this after dedup.
const MAX_PHOTOS = 20;
// Long side of each photo once downscaled for the vision request — plenty
// to make out what's in frame, small enough that even MAX_PHOTOS of them
// stay a cheap, fast request.
const RESIZE_WIDTH = 512;

function clockLabel(ms: number): string {
  const d = new Date(ms);
  let h = d.getHours();
  const m = String(d.getMinutes()).padStart(2, '0');
  const ap = h >= 12 ? 'PM' : 'AM';
  h = h % 12 || 12;
  return `${h}:${m} ${ap}`;
}

// A cheap fingerprint of exactly which photos — and which logged text —
// went into an analysis. If a day's photo set changes (more imported later)
// or the user edits/adds their own written memory, the signature changes
// too and the cache naturally regenerates instead of going stale forever.
function signatureOf(photos: TimedPhoto[], loggedText?: string): string {
  const photoPart = photos
    .map((p) => (p.source ? p.uri + '#' + p.source : p.uri))
    .sort()
    .join('|');
  return loggedText ? `${photoPart}::${loggedText}` : photoPart;
}

function dedupeAndCap(photos: TimedPhoto[]): TimedPhoto[] {
  const sorted = [...photos].sort((a, b) => a.takenAt - b.takenAt);
  const deduped: TimedPhoto[] = [];
  for (const p of sorted) {
    const last = deduped[deduped.length - 1];
    if (!last || p.takenAt - last.takenAt >= DUPLICATE_GAP_MS) deduped.push(p);
  }
  if (deduped.length <= MAX_PHOTOS) return deduped;
  // Even sample across the day, always keeping the first and last moment.
  const step = (deduped.length - 1) / (MAX_PHOTOS - 1);
  const sampled: TimedPhoto[] = [];
  for (let i = 0; i < MAX_PHOTOS; i++) sampled.push(deduped[Math.round(i * step)]);
  return sampled;
}

const BASE_PROMPT = `You reconstruct what a person's day looked like from their photos. You get the day's photos in order, each labeled with the clock time it was taken.

Write 2-4 sentences saying what they did, in order, with the actual times. Second person ("you"), past tense.

STYLE — this matters as much as accuracy:
- Concrete facts only: what, where, when. Nothing else.
- NO mood, atmosphere, or vibe words. Banned: "amazing", "beautiful", "cozy", "relaxing", "perfect", "lovely", "warm glow", "peaceful", "unwinding", "savoring", "setting the tone".
- NO speculation about how they felt or why they did something.
- Don't pad with hedges. State what the photos show, plainly. The app already labels this as photo-derived, so you don't need to keep saying "probably".
- Full sentences, natural voice — like a friend recapping the day back to you, not a bullet list and not a travel blog.

Good: "You were at the aquarium mid-afternoon — a while at the jellyfish tank, then over to the sharks. Home by 6."
Bad: "It looks like you spent a lovely afternoon at the aquarium, perhaps enjoying the peaceful glow of the jellyfish tank before wandering over to see the sharks."

SCREENSHOTS AND SAVED IMAGES — read this carefully:
Some images are labelled (SCREENSHOT, or saved from WhatsApp/Instagram/etc). Those were SAVED on that day, not photographed on that day. They are evidence of what the person looked at or received, NEVER evidence of where they were or what they did.
- A screenshot of flight details on the 3rd means they looked at a booking on the 3rd. It does NOT mean they flew on the 3rd. If the image itself states a date, that date belongs to the thing shown, not to this day.
- Never place the person at a location because a screenshot or saved image showed it.
- Mention one only if it's worth remembering, and say what it actually was: "you saved your flight details for the 12th", not "you flew".
- If a day has ONLY screenshots and saved images, then nothing is known about what the person actually did that day. Say that plainly and briefly — do not invent a day around the screenshots.

ACCURACY:
- Only what's actually visible. Never invent names, relationships, or specific places you can't see evidence of (turnstiles = "the subway", not a named station).
- If the photos are unclear or show very little, say so briefly rather than inventing a day.
- Never guess anything sensitive, medical, or negative about a person.

Respond with ONLY a JSON object: {"summary": "..."}`;

const LOGGED_TEXT_ADDENDUM = `

The user already wrote this about their day themselves — treat it as ground truth, never repeat or contradict it:
"{{loggedText}}"

Your job now is to COMPLEMENT it, not replace it: use the photos to fill in what that account doesn't cover (other times of day, other moments the photos show), so together they read as one fuller picture of the day. Weave in naturally — reference their account only in passing if it helps the flow (e.g. "before/after that..."), never restate it.`;

async function toDataUri(uri: string): Promise<string | null> {
  try {
    // A photo whose original is still in iCloud is stored as an OS asset
    // reference, which the manipulator can't read — resolve it to a real
    // file first. This is why analysis quietly produced nothing for older
    // days (the ones most likely to be offloaded) while recent days worked.
    const readable = await resolvePhotoUri(uri);
    if (!readable) return null;

    const result = await manipulateAsync(readable, [{ resize: { width: RESIZE_WIDTH } }], {
      compress: 0.5,
      format: SaveFormat.JPEG,
      base64: true,
    });
    if (result.base64) return `data:image/jpeg;base64,${result.base64}`;
    // Some platforms don't return base64 inline even when asked — read the
    // resized file directly as a fallback.
    const b64 = await FileSystem.readAsStringAsync(result.uri, { encoding: 'base64' });
    return `data:image/jpeg;base64,${b64}`;
  } catch {
    return null; // skip this one photo rather than fail the whole day
  }
}

async function generate(photos: TimedPhoto[], loggedText?: string): Promise<string | null> {
  const providers = visionProviders();
  if (providers.length === 0) return null;

  const chosen = dedupeAndCap(photos);
  if (chosen.length === 0) return null;

  const images = await Promise.all(chosen.map((p) => toDataUri(p.uri)));
  const content: Array<Record<string, unknown>> = [];
  chosen.forEach((p, i) => {
    const uri = images[i];
    if (!uri) return; // this one photo failed to encode — skip it, not the whole day
    const kind = p.source
      ? p.source === 'screenshot'
        ? ' — SCREENSHOT, saved this day, not taken this day'
        : ` — saved from ${p.source} this day, not taken this day`
      : '';
    content.push({ type: 'text', text: `Photo at ${clockLabel(p.takenAt)}${kind}:` });
    // 'low' detail costs a flat ~85 tokens per image regardless of size,
    // vs. hundreds-to-1000+ at the default 'auto'/high-detail tiling. Since
    // every image is already downscaled to RESIZE_WIDTH before this point,
    // high-detail mode would mostly be re-processing resolution that's
    // already gone — the quality loss is minimal, the token savings are
    // not (this was the actual cause of the real TPM exhaustion behind
    // "sending too fast", not request timing).
    content.push({ type: 'image_url', image_url: { url: uri, detail: 'low' } });
  });
  if (content.length === 0) return null;

  const systemPrompt = loggedText
    ? BASE_PROMPT + LOGGED_TEXT_ADDENDUM.replace('{{loggedText}}', loggedText)
    : BASE_PROMPT;

  // Cheapest capable provider first, OpenAI behind it — see aiProviders.ts.
  const result = await chatCompletion(providers, (model) => ({
    model,
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content },
    ],
    response_format: { type: 'json_object' },
    temperature: 0.5,
  }));
  if (!result.ok) return null;

  try {
    const parsed = JSON.parse(result.content) as { summary?: string };
    return parsed.summary?.trim() || null;
  } catch {
    return null;
  }
}

async function readCache(dayKey: string): Promise<AssumedMemory | null> {
  const raw = await AsyncStorage.getItem(CACHE_PREFIX + dayKey);
  return raw ? (JSON.parse(raw) as AssumedMemory) : null;
}

async function writeCache(dayKey: string, record: AssumedMemory): Promise<void> {
  await AsyncStorage.setItem(CACHE_PREFIX + dayKey, JSON.stringify(record));
  for (const listener of listeners) listener(dayKey);
}

// Screens subscribe so a day analyzed by the BACKGROUND pass appears on
// its own, without the user having to tap that day to make it show up.
// Without this the Timeline fetched once per selection and, if the queue
// finished that day a moment later, silently stayed blank.
type AssumedMemoryListener = (dayKey: string) => void;
const listeners = new Set<AssumedMemoryListener>();

export function onAssumedMemoryUpdated(listener: AssumedMemoryListener): () => void {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
}

// Cache-only read — never triggers analysis. Used by the live-update
// subscribers, which only want what just landed.
export async function getCachedAssumedMemory(dayKey: string): Promise<AssumedMemory | null> {
  return readCache(dayKey);
}

// The main entry point — cached per day, keyed to exactly which photos were
// analyzed so a later import (more photos land on that day) regenerates
// instead of showing a stale guess. Returns null when unavailable (no API
// key, no timestamped photos, or the analysis failed) — the caller simply
// doesn't show a card rather than showing something broken.
export async function getAssumedMemory(
  dayKey: string,
  photos: TimedPhoto[],
  // The day's own logged text (if any) — when present, the analysis
  // complements it (fills gaps) instead of generating in a vacuum.
  loggedText?: string,
): Promise<AssumedMemory | null> {
  if (!assumedMemoryAvailable() || photos.length === 0) return null;

  const signature = signatureOf(photos, loggedText);
  const cached = await readCache(dayKey);
  if (isFresh(cached, signature)) return cached;

  const summary = await generate(photos, loggedText);
  if (!summary) return null;

  // Deliberately does NOT carry over the old record's translations — the
  // summary just changed, so a translation of the previous wording would be
  // wrong. They're re-fetched on demand the next time Translate is tapped.
  const record: AssumedMemory = {
    summary,
    generatedAt: new Date().toISOString(),
    signature,
    promptVersion: PROMPT_VERSION,
  };
  await writeCache(dayKey, record);
  return record;
}

// Every cached assumed-memory record, keyed by day — the whole year's worth
// of photo analysis the Ask chatbot draws on. Only ever returns what's
// already been analyzed (see backfillAssumedMemories to fill it in).
export async function getAllAssumedMemories(): Promise<Record<string, AssumedMemory>> {
  const keys = (await AsyncStorage.getAllKeys()).filter((k) => k.startsWith(CACHE_PREFIX));
  if (keys.length === 0) return {};
  const pairs = await AsyncStorage.multiGet(keys);
  const out: Record<string, AssumedMemory> = {};
  for (const [key, raw] of pairs) {
    if (!raw) continue;
    try {
      out[key.slice(CACHE_PREFIX.length)] = JSON.parse(raw) as AssumedMemory;
    } catch {
      // Skip a corrupted entry rather than fail the whole read.
    }
  }
  return out;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Recent days are the ones actually worth having ready fast — freshest in
// the user's mind, most likely to come up in Ask right after a big import —
// so they're paced tighter. Everything older still gets there, just spread
// out more since there's no urgency. This is "recent batch fast, then the
// rest slowly" without needing separate discrete batches — a single
// newest-first queue with a recency-based pace produces exactly that shape.
//
// The real constraint here turned out to be OpenAI's TOKENS-per-minute
// limit, not request timing — confirmed directly against this account: a
// 200k TPM cap, fully exhausted by a handful of vision calls sent at
// default ('auto'/high) image detail. Switching to 'low' detail (see
// toDataUri's caller below) cuts each call from potentially 15,000+ tokens
// to a few hundred, which is the actual fix. This pacing is a second,
// independent safety margin on top of that — not the primary defense
// against exhausting the budget, so it stays conservative rather than
// trying to be fast.
const RECENT_WINDOW_DAYS = 90; // ~3 months
const RECENT_PACE_MS = 2000;
const OLDER_PACE_MS = 6000;
// Backoff after a failed attempt (see the loop below) — longer than either
// normal pace, since a failure signals the shared budget is tight, not just
// that it's this day's turn.
const FAILURE_BACKOFF_MS = 15000;

// Lets a live user request (a real Ask question) claim priority: the
// background pass checks this before firing its NEXT call and, if a
// question is in flight, waits for it rather than racing it. This is what
// actually stops the "sending questions too fast" collision — pacing alone
// only made it less likely, this makes it structurally impossible.
let priorityUntil = 0;
// Open-ended holds (as opposed to the timed pause below). The Ask screen
// takes one for as long as it's on screen: while the user is in there, the
// background pass does nothing at all, so the whole token budget is
// available for answering questions.
let holds = 0;

// Called by askMemory() right before it makes its request.
export function pauseBackgroundAnalysis(forMs = 6000): void {
  priorityUntil = Math.max(priorityUntil, Date.now() + forMs);
}

// Held for as long as the returned release function hasn't been called —
// designed to be returned straight out of a useEffect so it releases on
// unmount. Counted, so overlapping holders can't release each other early.
export function holdBackgroundAnalysis(): () => void {
  holds += 1;
  let released = false;
  return () => {
    if (released) return;
    released = true;
    holds = Math.max(0, holds - 1);
  };
}

function liveRequestInFlight(): boolean {
  return holds > 0 || Date.now() < priorityUntil;
}

function daysAgo(day: string): number {
  const d = new Date(`${day}T00:00:00`);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return Math.round((today.getTime() - d.getTime()) / 86400000);
}

// Guards against two overlapping runs (e.g. one kicked off after import
// while another is still mid-pass from opening Chat) stacking their
// requests on top of each other. No time-based cooldown beyond this — a
// day that's already cached costs nothing to re-check (getAssumedMemory
// no-ops without an API call), so there's no real cost to walking the log
// again on every open; the only thing worth guarding against is genuinely
// concurrent runs and bursty pacing, both handled below.
let backfillInFlight = false;

// Walks every day that has real photos and analyzes any that aren't
// already cached (or whose photos/logged text changed since), newest day
// first — so the Ask chatbot has the whole year's worth of photo analysis
// available, not just the handful of days the user happened to open on the
// Timeline, and the most useful (recent) days are ready first. The primary
// trigger is right after a photo import — before the user has any reason
// to be in Ask yet — with a lighter opportunistic re-check when Ask opens,
// as a safety net for anything interrupted (e.g. the app closed mid-pass).
// Paced by recency (see above) so it never bursts past the per-minute rate
// limit the user's own requests also share.
export async function backfillAssumedMemories(onProgress?: (done: number, total: number) => void): Promise<{
  analyzed: number;
}> {
  if (!assumedMemoryAvailable() || backfillInFlight) return { analyzed: 0 };

  backfillInFlight = true;
  try {
    // Everything is read ONCE up front. The previous version re-read the
    // whole photo-meta blob and the day's cache entry inside the loop —
    // for a year of photos that's hundreds of full storage reads, which is
    // what made a fully-cached "catch-up" still take many seconds and
    // show its banner all over again.
    const all = await getLoggedMemories();
    const allTimestamps = await getAllPhotoTimestamps();
    const allSources = await getAllPhotoSources();
    const cached = await getAllAssumedMemories();

    const byDay = new Map<string, LoggedMemory[]>();
    for (const m of all) {
      const key = dateKey(new Date(m.takenAt));
      const bucket = byDay.get(key) ?? [];
      bucket.push(m);
      byDay.set(key, bucket);
    }

    // Work out up front which days actually need an API call, so the
    // progress count reflects real remaining work rather than counting
    // hundreds of already-done days.
    const pending: { day: string; photos: TimedPhoto[]; loggedText?: string }[] = [];
    for (const [day, memories] of byDay) {
      const uris = memories.flatMap((m) => (m.kind === 'photo' ? (m.photoUris ?? []) : []));
      const photos = uris
        .filter((u) => allTimestamps[u])
        .map((u) => ({ uri: u, takenAt: allTimestamps[u], source: allSources[u] }));
      if (photos.length === 0) continue;
      const loggedText = dayLoggedText(memories) || undefined;
      // Same freshness check getAssumedMemory does internally — done here
      // against the already-loaded cache so we never touch storage per day.
      if (isFresh(cached[day], signatureOf(photos, loggedText))) continue;
      pending.push({ day, photos, loggedText });
    }
    pending.sort((a, b) => b.day.localeCompare(a.day)); // newest first

    // Days a question just asked about jump the queue. Older days
    // otherwise sit at the back of a newest-first queue paced at one every
    // six seconds, which for a day in February means the user would be
    // waiting a very long time for an answer about it.
    if (prioritized.size > 0) {
      pending.sort((a, b) => Number(prioritized.has(b.day)) - Number(prioritized.has(a.day)));
    }

    let analyzed = 0;
    for (const { day, photos, loggedText } of pending) {
      // Step aside for a live question rather than racing it — poll
      // briefly until it's done instead of firing anyway and hoping.
      while (liveRequestInFlight()) await sleep(300);

      const record = await getAssumedMemory(day, photos, loggedText);
      analyzed++;
      onProgress?.(analyzed, pending.length);
      if (record) {
        const pace = daysAgo(day) <= RECENT_WINDOW_DAYS ? RECENT_PACE_MS : OLDER_PACE_MS;
        await sleep(pace);
      } else {
        // A failed attempt is almost always the token-per-minute budget
        // being tight right now — back off well beyond the normal pace
        // before the next try, instead of hammering straight through every
        // remaining day with no gap (which is what kept the budget pinned
        // at zero and made the very next live question fail too).
        await sleep(FAILURE_BACKOFF_MS);
      }
    }
    return { analyzed };
  } finally {
    backfillInFlight = false;
  }
}

// Days that a live question pointed at, so the background pass reaches
// them before the rest of its newest-first queue. Bounded — this is a
// nudge, not a second queue.
const prioritized = new Set<string>();

export function prioritizeDays(days: string[]): void {
  for (const day of days) prioritized.add(day);
  // Keep only the most recently requested handful, so a long session's
  // worth of questions doesn't end up prioritising everything (which
  // prioritises nothing).
  while (prioritized.size > 12) prioritized.delete(prioritized.values().next().value as string);
}

// How many days one question is allowed to analyze on the spot. A question
// about a single day (the usual case) is worth the few seconds; a question
// spanning a whole month is not — those days get prioritized in the
// background pass instead, and the answer says the photos aren't read yet.
const MAX_ON_DEMAND_DAYS = 2;

// Reads the photos for specific days RIGHT NOW, rather than waiting for the
// background pass to reach them.
//
// This is what makes a question about an old day work at all. The
// background pass goes newest-first, so a day from February is hundreds of
// days down the queue; without this, "what did I do on the first day of
// Ramadan?" could only ever answer "there are photos but I haven't read
// them yet" — for weeks. Now the day the question is about gets read
// immediately, and the answer is a real one.
//
// Returns how many days it actually analyzed. Deliberately quiet: a day it
// can't do (no photos, already fresh, no API credit) is simply skipped, and
// the caller carries on and answers with whatever exists.
export async function analyzeDaysNow(
  days: string[],
  max = MAX_ON_DEMAND_DAYS,
): Promise<number> {
  if (!assumedMemoryAvailable() || days.length === 0) return 0;

  // Nudge the background pass regardless of what we manage to do here, so
  // anything skipped below still gets picked up soon rather than never.
  prioritizeDays(days);

  const wanted = new Set(days);
  const all = await getLoggedMemories();
  const byDay = new Map<string, LoggedMemory[]>();
  for (const m of all) {
    const key = dateKey(new Date(m.takenAt));
    if (!wanted.has(key)) continue;
    const bucket = byDay.get(key) ?? [];
    bucket.push(m);
    byDay.set(key, bucket);
  }
  if (byDay.size === 0) return 0;

  const allTimestamps = await getAllPhotoTimestamps();
  const allSources = await getAllPhotoSources();

  const todo: { day: string; photos: TimedPhoto[]; loggedText?: string }[] = [];
  for (const [day, memories] of byDay) {
    const uris = memories.flatMap((m) => (m.kind === 'photo' ? (m.photoUris ?? []) : []));
    const photos = uris
      .filter((u) => allTimestamps[u])
      .map((u) => ({ uri: u, takenAt: allTimestamps[u], source: allSources[u] }));
    if (photos.length === 0) continue;
    const loggedText = dayLoggedText(memories) || undefined;
    if (isFresh(await readCache(day), signatureOf(photos, loggedText))) continue;
    todo.push({ day, photos, loggedText });
  }
  if (todo.length === 0) return 0;

  // The caller's order is the priority order — it knows which day the
  // question was actually about and which are just the days either side,
  // and that distinction is the whole point when only `max` get done.
  const rank = new Map(days.map((day, i) => [day, i]));
  todo.sort((a, b) => (rank.get(a.day) ?? 999) - (rank.get(b.day) ?? 999));

  let analyzed = 0;
  for (const { day, photos, loggedText } of todo.slice(0, max)) {
    const record = await getAssumedMemory(day, photos, loggedText);
    if (record) analyzed += 1;
  }
  return analyzed;
}

// Translates a day's assumed-memory summary into the given language,
// caching the result on that same record — so tapping "Translate" only
// ever costs one call per day per language, no matter how many times the
// card is reopened. Returns the translated text, or null if it couldn't be
// produced (no API key, or the request failed).
export async function translateAssumedMemory(
  dayKey: string,
  record: AssumedMemory,
  lang: string,
): Promise<string | null> {
  const cached = record.translations?.[lang];
  if (cached) return cached;

  const language = ASSUMED_MEMORY_LANGUAGES[lang];
  if (!language) return null;

  const result = await chatCompletion(textProviders(), (model) => ({
    model,
    messages: [
      {
        role: 'system',
        content: `Translate the user's message into ${language.instruction}

Keep it the same length and just as direct — don't add mood words, adjectives or flourishes that aren't in the original. Respond with ONLY the translated text, nothing else.`,
      },
      { role: 'user', content: record.summary },
    ],
    temperature: 0.2,
  }));
  if (!result.ok) return null;

  const translated = result.content.trim();
  if (!translated) return null;

  const updated: AssumedMemory = {
    ...record,
    translations: { ...record.translations, [lang]: translated },
  };
  await writeCache(dayKey, updated);
  return translated;
}

// Dismissing hides the card for that exact photo set — if new photos land
// on the day later (signature changes), it resurfaces on its own rather
// than staying hidden forever.
export async function isAssumedMemoryDismissed(dayKey: string, signature: string): Promise<boolean> {
  const raw = await AsyncStorage.getItem(DISMISSED_KEY);
  const map = raw ? (JSON.parse(raw) as Record<string, string>) : {};
  return map[dayKey] === signature;
}

export async function dismissAssumedMemory(dayKey: string, signature: string): Promise<void> {
  const raw = await AsyncStorage.getItem(DISMISSED_KEY);
  const map = raw ? (JSON.parse(raw) as Record<string, string>) : {};
  map[dayKey] = signature;
  await AsyncStorage.setItem(DISMISSED_KEY, JSON.stringify(map));
}
